## 3. 넘파이
넘파이란? 다차원배열과 수학 함수를 제공하는 모듈(라이브러리)  
모듈이란? 필요한 기능을 미리 만들어두고 가져다 쓰는 것

3.1 ndarry  
다차원 배열  
다차원 배열의 특징:  
1. 리스트와 비교했을 때 계산 속도가 빠름  
2. 리스트와 달리 모든 요소의 타입이 같음  

In [2]:
# 먼저 numpy 모듈 가져오기
# 외부에 있는 모듈 파일을 가지고 올때는 import
# 모듈의 이름이 길 때는 별칭 붙이기 as np
import numpy as np

In [3]:
# 넘파이 배열 만들기
# 입력값: 리스트
a = np.array([1,2,3])
a
b = np.array(['a','b','c'])
b

array(['a', 'b', 'c'], dtype='<U1')

NumPy 배열의 dtype으로 표시된 '<U1'은 다음 의미를 가집니다.

'U'는 Unicode 문자열 데이터 타입을 뜻하며, Python 3의 문자열은 기본적으로 Unicode입니다.

숫자 1은 문자열의 최대 길이가 1글자임을 나타냅니다.

예를 들어 np.array(['a','b','c'])를 생성하면 각 원소는 한 글자짜리 Unicode 문자열이라 dtype이 '<U1'로 표시됩니다.

즉, dtype='<U1'는 이 배열이 길이 1의 유니코드 문자열로 구성된 배열임을 의미합니다.

추가로,

만약 문자열 길이가 길면, 예를 들어 최대 10글자면 '<U10'로 표시됩니다.

숫자와 문자열이 섞이면 타입이 확장되어 더 긴 문자열 형태(dtype)로 변환될 수 있습니다.

요약: 배열 내부가 문자형이고 최대 1글자로 제한된 Unicode 문자열 배열임을 의미하는 dtype 표기입니다.

In [9]:
# 2차원 배열 생성
# 2차원 배열은 1차원 배열의 묶음
c = np.array([[1,2,3],[4,5,6]])
c
# 3행 3열 크기의 2차원 배열 생성
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# 주석 단축키 : ctrl + /
# arrange : 숫자 여러개를 생성하는 함수
# 0부터 연속된 숫자가 입력된 개수만큼 생성
a = np.arange(10)
# 1부터 10까지 생성
b = np.arange(1,11)
# 1부터 10까지 2씩 건너뛰면서 생성
c = np.arange(1,11,2)
c

array([1, 3, 5, 7, 9])

## 연습문제

In [14]:
scores = np.array([85,90,78,92,88])
scores

array([85, 90, 78, 92, 88])

In [16]:
heights = np.array([160,165,170,175,180])
heights

array([160, 165, 170, 175, 180])

In [17]:
price = np.array([1200,1500,1800,2100])
price

array([1200, 1500, 1800, 2100])

In [18]:
temps = np.array([20,22,19,25,30])
temps

array([20, 22, 19, 25, 30])

## 연습문제

In [19]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [20]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array = np.arange(3,8)
array

array([3, 4, 5, 6, 7])

In [22]:
array = np.arange(-2,3)
array

array([-2, -1,  0,  1,  2])

In [23]:
# zeros : 배열을 생성하고 값을 0으로 초기화
# 10개 크기의 배열 생성
np.zeros(10)
# 2차원 배열 생성
np.zeros((3,3)) # 행 열

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# 1차원 배열 생성
# 파이썬의 리스트와 달리, 넘파이 배열은 모든 원소의 자료형이 같다.
a = np.array([1,2,3])
# 배열의 정보를 확인
print(a.dtype) # 자료형
print(a.ndim)  # 차원
print(a.shape) # 크기

int64
1
(3,)


In [26]:
# 2차원 배열 생성
# 2행 3열 2차원 배열 생성
b = np.array([[1,2,3],[4,5,6]])
print(b.dtype)
print(b.ndim)
print(b.shape)

int64
2
(2, 3)


In [236]:
# 실수형 1차원 배열 생성
arr = np.array([1.1, 2.1, 3.1])
# 자료형 확인
arr.dtype
# 배열의 형변환
# float -> int
arr2 = arr.astype(np.int32)
arr2.dtype

dtype('int32')

In [31]:
# 파이썬의 리스트 생성
lis = [1,2,3]
# 파이썬의 각 원소에 3씩 더하기
# 리스트의 원소에 하나씩 계산하려면 for 반복문을 사용해야 한다.
for i in lis :
    print(i+3)

4
5
6


In [33]:
# 넘파이 배열 생성
# 넘파이 배열은 for문 없이 각 원소에 값을 계산할 수 있다.
# 넘파이 배열은 자동으로 각 원소에 반복 수행이 된다.
a = np.array([1,2,3])
# 각 원소에 3씩 더하기
a + 3

array([4, 5, 6])

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# 배열 두개를 비교
a > b

array([False, False, False])

## 인덱스와 슬라이스

In [40]:
# 0~9 숫자 만들고 1차원 배열 생성
a = np.arange(10)
print(a)
# 배열의 우너소 하나 꺼내기
a[1]
# 범위로 값 꺼내기 (슬라이스)
a[3:6]
# 원소 값 변경하기
# 두번째 원소의 값 변경하기
a[1] = 99
a
# 특정 범위에 있는 값을 모두 변경하기
# 3,4,5 번째 데이터 변경
a[3:6] = 88
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

In [41]:
# 배열 전체 선택
# a를 출력하는 것과 같다.
a[:]

array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

In [42]:
# 슬라이스로 배열 전체를 선택하고, 값 변경
a[:] = 999
a

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

## 연습문제

In [44]:
arr = np.array([10,20,30,40,50,])
arr[0]

np.int64(10)

In [45]:
arr[2]

np.int64(30)

In [46]:
arr[-1]

np.int64(50)

In [48]:
arr[1] = 200
arr

array([ 10, 200,  30,  40,  50])

In [49]:
arr[3] = 999
arr

array([ 10, 200,  30, 999,  50])

In [50]:
arr = np.array(['가','나','다','라','마'])
arr[1]

np.str_('나')

In [51]:
arr[3]

np.str_('라')

In [52]:
arr[-1]

np.str_('마')

In [54]:
arr[0] = '하'
arr

array(['하', '나', '다', '라', '마'], dtype='<U1')

In [55]:
arr[2] ='호'
arr

array(['하', '나', '호', '라', '마'], dtype='<U1')

In [57]:
arr = np.array([10,20,30,40,50,60,70])
arr[0:3]

array([10, 20, 30])

In [59]:
arr[3:]

array([40, 50, 60, 70])

In [61]:
arr[1:5]

array([20, 30, 40, 50])

In [63]:
arr = np.array(['a','b','c','d','e','f','g'])
arr[0:3]

array(['a', 'b', 'c'], dtype='<U1')

In [65]:
arr[3: ]

array(['d', 'e', 'f', 'g'], dtype='<U1')

In [67]:
arr[1:5]

array(['b', 'c', 'd', 'e'], dtype='<U1')

## 2차원 배열의 인덱싱

In [5]:
# 3행 3열 2차원 배열 생성
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
# 2차원 배열의 인덱스
arr[2]

array([7, 8, 9])

In [72]:
# 2차원 배열의 인덱스
# 행 (인덱스)  열(컬럼)
# 첫번째 행 꺼내기
arr[0]

array([1, 2, 3])

In [75]:
# 1 꺼내기
arr[0][0]  # [행][열]
# 9 꺼내기
arr[2][2]
# 5 꺼내기
arr[1][1]
# 간단하게 쓰기
arr[1,1]

np.int64(5)

In [8]:
arr[1, 2]

np.int64(6)

In [77]:
# 배열 원소의 값 바꾸기
# 0 -> 1
arr[0,0] = 0
arr
arr[1][1] = 0
arr

array([[0, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

## 2차원 배열 슬라이스

In [79]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
# 행을 기준으로 슬라이스
# 처음부터 두번째 행까지
arr[ :2]

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
# 행 : 1번, 2번
# 열 : 1번, 2번
arr[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [83]:
# 행 : 0,1
# 열 : 0,1
arr[ :2, :2]

array([[1, 2],
       [4, 5]])

In [84]:
# 행 : 1
# 열 : 0,1
arr[ 1, 0:2]

array([4, 5])

In [10]:
arr[ : , 1]

array([2, 5, 8])

In [13]:
arr[2, 1] = 88
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 88,  9]])

In [86]:
arr = np.array([[10,20,30],
               [40,50,60,],
               [70,80,90]])

In [87]:
arr[0,1]

np.int64(20)

In [88]:
arr[2,0]

np.int64(70)

In [90]:
arr[1]

array([40, 50, 60])

In [94]:
arr[ :, 1]

array([20, 50, 80])

In [97]:
arr[0,2] = 300
arr

array([[ 10,  20, 300],
       [ 40,  50,  60],
       [ 70,  80,  90]])

In [103]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

In [104]:
arr[1,2]

np.int64(7)

In [105]:
arr[3,0]

np.int64(13)

In [107]:
arr[2]

array([ 9, 10, 11, 12])

In [108]:
arr[:,3]

array([ 4,  8, 12, 16])

In [110]:
arr[0,3] = 100
arr

array([[  1,   2,   3, 100],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [112]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [114]:
arr[0,:2]

array([10, 20])

In [115]:
arr[1:3]

array([[40, 50, 60],
       [70, 80, 90]])

In [118]:
arr[:,1:3]

array([[20, 30],
       [50, 60],
       [80, 90]])

## 불리언 인덱스  
인덱스란? 데이터의 위치  

In [156]:
# 학생 배열 생성
students = np.array(['철수','영희','민수','철수','철수'])
# 학생들의 대출 이력 (책제목, 대출일)
books = np.array([['수학의정석', 7], ['해리포터', 10],['파이썬 입문', 5],
                  ['한국사', 5],['데미안',12]])

In [157]:
# 철수의 대출 이력
# 배열 == '비교값'
# 배열 전체에 철수를 비교
# 총 5번 비교하고 bool 배열 반환
arr = students == '철수'
arr

array([ True, False, False,  True,  True])

In [158]:
# books 배열의 인덱스에 bool 배열 넣기
# true 에 해당하는 원소만 반환
# 조건에 맞는 원소를 꺼낼 때 사용
books[students == '철수']

array([['수학의정석', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [159]:
print(students != '철수')
# 철수가 아닌 대출 이력 찾기
books[students != '철수']

[False  True  True False False]


array([['해리포터', '10'],
       ['파이썬 입문', '5']], dtype='<U21')

In [165]:
# '수학의 정석' 을 찾아서 제목을 '자바의 정석' 으로 바꾸기
print(books == '수학의정석')
#
books[books == '수학의 정석'] = '자바의 정석'
books

[[ True False]
 [False False]
 [False False]
 [False False]
 [False False]]


array([['수학의정석', '7'],
       ['해리포터', '10'],
       ['파이썬 입문', '5'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [141]:
# 대출이력 중에서 철수가 아닌 항목을 찾고
# 행 전체를 7로 바꾸기
students != '철수'

array([False,  True,  True, False, False])

In [144]:
books[students != '철수' ] = 7
books

array([['수학의정석', '7'],
       ['7', '7'],
       ['7', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

## 연습문제

In [164]:
arr = np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [163]:
arr > 30

array([False, False, False,  True,  True,  True,  True])

In [148]:
arr[arr > 30]

array([40, 50, 60, 70])

In [149]:
arr[arr %2 == 0 ]

array([10, 20, 30, 40, 50, 60, 70])

In [150]:
arr[arr > 50] = 999
arr

array([ 10,  20,  30,  40,  50, 999, 999])

In [151]:
arr

array([ 10,  20,  30,  40,  50, 999, 999])

In [166]:
employees = np.array(['짱구','철수','유리','맹구','훈이'])

In [167]:
salaries = np.array([250,320,280,400,150])

In [168]:
employees == '맹구'

array([False, False, False,  True, False])

In [169]:
salaries[employees == '맹구']

array([400])

In [170]:
employees[ salaries >= 300]

array(['철수', '맹구'], dtype='<U2')

In [172]:
salaries[salaries < 200] == 200
salaries

array([250, 320, 280, 400, 150])

## 3.2 배열의 모양 바꾸기

In [174]:
# 1~9 숫자가 담긴 1차원 배열 생성
# reshape : 배열의 형태를 바꾸는 함수
# 1차원 -> 2차원
# 3행 3열 크기의 배열로 변환
print(np.arange(1,10))
arr = np.arange(1,10).reshape(3,3)
arr

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
# 1~16 숫자가 담긴 1차원 배열
# 1차원 -> 2차원
print(np.arange(1,17))
a = np.arange(1,17).reshape(4,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [180]:
# 1~12 1차원 배열
# 이 배열을 3행 4열 배열로 변환
print( np.arange(1,13))
a = np.arange(1,13).reshape(3,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 연습

In [183]:
print(np.arange(12))
a = np.arange(12).reshape(3,4)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
print(np.arange(1,17))
a = np.arange(1,17).reshape(4,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [185]:
print(np.arange(1,21))
a = (np.arange(1,21)).reshape(5,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [188]:
print(np.arange(10,26))
a = np.arange(10,26).reshape(4,4)
a

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

## 3.3 난수를 생성하는 방법
난수란? 랜덤값

In [190]:
# 랜덤값 만들기
# 표준 정규 분포 : 표준 편차가 1인 그래프에서 랜덤값을 생성 (-3 ~ 3 )
# 랜덤값 10개 생성
arr = np.random.standard_normal(size=10)
arr

array([-1.86589012, -0.42516576, -1.78764104, -0.17296027, -0.96132173,
        0.90972146,  0.71620697,  0.38375484,  0.88314475,  1.2999116 ])

In [191]:
# 균일 분포 : 범위 0~1. 모든 값이 같은 확률로 나옴
arr = np.random.uniform(size=10)
arr

array([0.34923668, 0.24297485, 0.98411645, 0.89246863, 0.75625664,
       0.04204743, 0.60880747, 0.28317293, 0.01215893, 0.22901874])

In [192]:
# 표준 정규 분포 에서 랜덤값 5개 생성
arr = np.random.standard_normal(size = 5)
arr

array([-2.00279123, -1.3741257 ,  0.12916407,  1.15598253, -0.08754346])

In [193]:
# 균일 분포에서 랜덤값 5개 생성
arr = np.random.uniform(size = 5)
arr

array([0.59869991, 0.38720983, 0.95707661, 0.20052683, 0.55384675])

## 3.4 유니버설 함수
반복문 없이 배열 전체에 계산을 해주는 함수

In [194]:
# 0~9 숫자가 담긴 1차원 배열 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
# 파이썬의 리스트는 for문을 사용해서 계산해야함
# 넘파이의 배열은 for문 없이 계산 가능

# 배열 전체에 3 더하기
# add : 더하기 (원본데이터, 원본데이터 + 더할 값)
np.add(arr, 3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [199]:
a = np.array([1,7,2,4,10])
b = np.array([3,4,5,6,7])

# 두 배열을 비교하여 더 큰값 저장하기
np.maximum(a,b)

array([ 3,  7,  5,  6, 10])

## 조건문

In [201]:
# 배열 두개 만들기
a = np.array([1,2,3])
b = np.array([10,20,30])
# 불리언 배열 만들기(조건) -> 개수가 같아야한다
cond = np.array([True, True, False])

In [203]:
# 조건문 쓰기 : where(조건, 참일때값, 거짓일때값)
# 조건이 참이면 a 에서 값을 선택, 거짓이면 b 에서 값을 선택
# where 는 삼항 연산자와 비슷
result = np.where(cond, a, b)
result

array([ 1,  2, 30])

In [209]:
# 1차원 배열 생성
arr = np.array([-2,-1,0,1,2])

# 양수면 'o' 음수면 'x' 로 반환
# 조건, 참일때값, 거짓일때값
print(arr > 0)
np.where(arr > 0, 'o','x')

[False False False  True  True]


array(['x', 'x', 'x', 'o', 'o'], dtype='<U1')

## 연습문제

In [211]:
arr = np.array([5,12,7,20,3])
arr

array([ 5, 12,  7, 20,  3])

In [213]:
np.where(arr > 10, '100', '0')

array(['0', '100', '0', '100', '0'], dtype='<U3')

In [214]:
arr = np.array([15,8,22,6,13])
arr

array([15,  8, 22,  6, 13])

In [215]:
np.where(arr % 2 == 0, 1, -1)

array([-1,  1,  1,  1, -1])

In [216]:
arr = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])
cond = np.array([True, True, False, False, True])
np.where(cond == True, arr, arr2)

array([10, 20,  3,  4, 50])

## 통계를 구할 때 자주 사용하는 함수들
(최대 최소 합계 평균)

In [217]:
# 파이썬의 리스트 생성
lis = [1,2,3,4,5]
# 리스트의 총합을 구하세요
sum = 0
for i in lis:
    sum = sum +i
print(sum)
# 리스트의 평균을 구하세요
print(sum/len(lis))

15
3.0


In [221]:
# 넘파이 배열로 합계와 평균 구하기
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.average(arr))
# 배열에서 제일 큰 값
print(np.max(arr))
# 배열에서 제일 작은 값
print(np.min(arr))

15
3.0
5
1


In [223]:
arr = np.array([250,550,400,800])
print(np.sum(arr))
print(np.average(arr))
print(np.max(arr))
print(np.min(arr))

2000
500.0
800
250


## 행/열 단위로 합계 구하기

In [227]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

# 배열의 합계 구하기
arr.sum()
# 2차원 배열에서 행 또는 열 방향으로 합 구하기
# axis = 0 : 세로 방향으로 합 계산
# axis = 1 : 가로 방향으로 합 계산
arr.sum(axis=0)
arr.sum(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [230]:
# 누적값 구하기
# 합을 구하는 중간 과정을 보여줌
arr = np.array([1,2,3,4,5])
print(arr.sum())
arr.cumsum()

15


array([ 1,  3,  6, 10, 15])

In [235]:
# 3행 3열 2차원 배열 생성
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)
# 2차원 배열의 누적값 구하기
# 기준 설정
print(arr.cumsum(axis=0))
#
print(arr.cumsum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
